package progpattproject;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author melis
 */
public class LibrarianForm extends javax.swing.JFrame {

    private ResourceBundle bundle;
    private ResourceBundle bundleFR;
    
    /**
     * Creates new form LibrarianForm
     */
    public LibrarianForm() {
        initComponents();
        
        bundle = ResourceBundle.getBundle("FormLanguage");
        bundleFR = ResourceBundle.getBundle("FormLanguage", Locale.FRANCE);
    }
    
    public void tableUpdate() {
        DefaultTableModel model = (DefaultTableModel) studentTable.getModel();
        model.setRowCount(0);
        
        Controller.getInstance().getLibCon().updateArrays();
        ArrayList<Student> students = Controller.getInstance().getLibCon().getStudents();
        
        for(Student s : students) {
            Object[] o = new Object[]{s.getStId(), s.getName(), s.getContactNumber()};
            model.addRow(o);
        }
        model.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        menuButton = new javax.swing.JButton();
        englishButton = new javax.swing.JRadioButton();
        frenchButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        studentLabel = new javax.swing.JLabel();
        stuIDLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        phoneNumLabel = new javax.swing.JLabel();
        addStuBtn = new javax.swing.JButton();
        stuIDInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        phoneInput = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        issueLabel = new javax.swing.JLabel();
        issueSNNum = new javax.swing.JLabel();
        issueStuID = new javax.swing.JLabel();
        issueBookStuIDInput = new javax.swing.JTextField();
        issueBookSNInput = new javax.swing.JTextField();
        issueBookBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        returnLabel = new javax.swing.JLabel();
        returnSNNum = new javax.swing.JLabel();
        returnStuIDLabel = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        returnStuID = new javax.swing.JTextField();
        returnSerialNum = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        listLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        catalogueTextArea = new javax.swing.JTextArea();
        allBooksBtn = new javax.swing.JButton();
        issuedBooksBtn = new javax.swing.JButton();
        catalogueLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addBookLabel = new javax.swing.JLabel();
        addBookSNNum = new javax.swing.JLabel();
        addBookSN = new javax.swing.JTextField();
        addBookTitle = new javax.swing.JTextField();
        addBookAuthor = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        publisherLabel = new javax.swing.JLabel();
        addBookPublisher = new javax.swing.JTextField();
        addBookPrice = new javax.swing.JTextField();
        addBookQTY = new javax.swing.JTextField();
        addBookQTYIssued = new javax.swing.JTextField();
        addBookDate = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        qtyLabel = new javax.swing.JLabel();
        qtyIssuedLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        addBookBtn = new javax.swing.JButton();
        textArea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        menuButton.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        menuButton.setText("Return to Previous Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(englishButton);
        englishButton.setText("English");
        englishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(frenchButton);
        frenchButton.setText("French");
        frenchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        studentLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        studentLabel.setText("Add Student");

        stuIDLabel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        stuIDLabel.setText("Student ID:");

        nameLabel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        nameLabel.setText("Name: ");

        phoneNumLabel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        phoneNumLabel.setText("Phone Number:");

        addStuBtn.setText("Add");
        addStuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stuIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stuIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(phoneInput))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(addStuBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(studentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuIDLabel)
                    .addComponent(stuIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumLabel)
                    .addComponent(phoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addStuBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        issueLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        issueLabel.setText("Issue a Book");

        issueSNNum.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        issueSNNum.setText("SN");

        issueStuID.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        issueStuID.setText("Student ID");

        issueBookStuIDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookStuIDInputActionPerformed(evt);
            }
        });

        issueBookBtn.setText("Issue");
        issueBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(issueBookBtn)
                .addGap(74, 74, 74))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(issueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issueSNNum, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issueStuID, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issueBookStuIDInput, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(issueBookSNInput))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(issueLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueSNNum)
                    .addComponent(issueBookSNInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueStuID)
                    .addComponent(issueBookStuIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(issueBookBtn)
                .addGap(27, 27, 27))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        returnLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        returnLabel.setText("Return a Book");

        returnSNNum.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        returnSNNum.setText("SN");

        returnStuIDLabel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        returnStuIDLabel.setText("Student ID");

        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(returnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returnSNNum, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnStuIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returnStuID)
                            .addComponent(returnSerialNum))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 96, Short.MAX_VALUE)
                        .addComponent(returnBtn)
                        .addGap(90, 90, 90))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(returnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnSNNum)
                    .addComponent(returnSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnStuIDLabel)
                    .addComponent(returnStuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(returnBtn)
                .addGap(17, 17, 17))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        listLabel.setText("List of Students");

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(studentTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        catalogueTextArea.setColumns(20);
        catalogueTextArea.setRows(5);
        jScrollPane2.setViewportView(catalogueTextArea);

        allBooksBtn.setText("View All Books");
        allBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBooksBtnActionPerformed(evt);
            }
        });

        issuedBooksBtn.setText("View Issued Books");
        issuedBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedBooksBtnActionPerformed(evt);
            }
        });

        catalogueLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        catalogueLabel.setText("Book Catalogue");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(allBooksBtn)
                        .addGap(69, 69, 69)
                        .addComponent(issuedBooksBtn)
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catalogueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(catalogueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allBooksBtn)
                    .addComponent(issuedBooksBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addBookLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        addBookLabel.setText("Add a Book");

        addBookSNNum.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        addBookSNNum.setText("SN");

        titleLabel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        titleLabel.setText("Title");

        authorLabel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        authorLabel.setText("Author");

        publisherLabel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        publisherLabel.setText("Publisher");

        addBookPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookPublisherActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        priceLabel.setText("Price");

        qtyLabel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        qtyLabel.setText("Quantity");

        qtyIssuedLabel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        qtyIssuedLabel.setText("Quantity Issued");

        dateLabel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        dateLabel.setText("Date");

        addBookBtn.setText("Add");
        addBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addBookSNNum, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(publisherLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyIssuedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBookTitle)
                            .addComponent(addBookSN)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addBookPublisher)
                            .addComponent(addBookPrice)
                            .addComponent(addBookQTY)
                            .addComponent(addBookQTYIssued)
                            .addComponent(addBookDate)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(addBookBtn))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(addBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(addBookLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookSNNum)
                    .addComponent(addBookSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publisherLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookQTYIssued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyIssuedLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel))
                .addGap(18, 18, 18)
                .addComponent(addBookBtn)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frenchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(englishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menuButton)
                            .addComponent(englishButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frenchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issueBookStuIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookStuIDInputActionPerformed
        
    }//GEN-LAST:event_issueBookStuIDInputActionPerformed

    private void addBookPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBookPublisherActionPerformed

    private void addStuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStuBtnActionPerformed
        try {
            int studentID = Integer.parseInt(stuIDInput.getText());
            String stuName = nameInput.getText();
            String phone = phoneInput.getText();

            Student student = new Student(studentID, stuName, phone);
            Controller.getInstance().getLibCon().getStudents().get(0).addStudent(student);
            
            textArea.setText("Student Added!");
        }
        catch (SQLException ex){
            textArea.setText("Error");
        }
        tableUpdate();
    }//GEN-LAST:event_addStuBtnActionPerformed

    private void issueBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookBtnActionPerformed
        try {
            ArrayList<Book> books = Controller.getInstance().getLibCon().getBooks();
            ArrayList<Student> students = Controller.getInstance().getLibCon().getStudents();
            Book tempBook = null;
            Student tempStudent = null;
            for (Book b : books) {
                if (b.getSN().equals(issueBookSNInput.getText())) {
                    tempBook = b;
                }
            }
            for (Student s : students) {
                if (s.getStId() == Integer.parseInt(issueBookStuIDInput.getText())) {
                    tempStudent = s;
                }
            }
            if(tempBook != null && tempStudent != null) {
                tempBook.issueBook(tempBook, tempStudent);
                textArea.setText("Book Issued!");
            }
            else
                textArea.setText("No Book or Student");
        } catch (SQLException ex) {
             textArea.setText("Error");
        }
    }//GEN-LAST:event_issueBookBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        try {
            ArrayList<Book> books = Controller.getInstance().getLibCon().getBooks();
            ArrayList<Student> students = Controller.getInstance().getLibCon().getStudents();
            
            Book tempBook = null;
            Student tempStudent = null;
            
            for (Book b : books) {
                if (b.getSN().equals(returnSerialNum.getText())) {
                    tempBook = b;
                }
            }
            for (Student s : students) {
                if (s.getStId() == Integer.parseInt(returnStuID.getText())) {
                    tempStudent = s;
                }
            }
            if(tempBook != null && tempStudent != null) {
                tempBook.returnBook(tempBook, tempStudent);
                textArea.setText("Book Returned!");
            }
            else
                textArea.setText("No Book or Student");
        } catch (SQLException ex) {
            textArea.setText("Error");
        }
    }//GEN-LAST:event_returnBtnActionPerformed

    private void addBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookBtnActionPerformed
        try {
            String SN = addBookSN.getText();
            String tempTitle = addBookTitle.getText();
            String author = addBookAuthor.getText();
            String publisher = addBookPublisher.getText();
            double price = Double.parseDouble(addBookPrice.getText());
            int qte = Integer.parseInt(addBookQTY.getText());
            int issuedQte = Integer.parseInt(addBookQTYIssued.getText());
            String tempDate = addBookDate.getText();
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            LocalDate localDate = LocalDate.parse(tempDate, formatter);
            
            Book tempBook = new Book(SN, tempTitle, author, publisher, price, qte, issuedQte, localDate);
            Controller.getInstance().getLibCon().getBooks().get(0).addBook(tempBook);  
            
            textArea.setText("Added Book!");
        } 
        catch (SQLException ex) {
            textArea.setText("Error");           
        }
    }//GEN-LAST:event_addBookBtnActionPerformed

    private void allBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBooksBtnActionPerformed
        catalogueTextArea.setText("");
        
        Map<String, String> map = Book.viewCatalog();
        for (Map.Entry<String, String> entry : map.entrySet()) {
            catalogueTextArea.append(entry.toString() +"\n");
        }
    }//GEN-LAST:event_allBooksBtnActionPerformed

    private void issuedBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedBooksBtnActionPerformed
        catalogueTextArea.setText("");
        Map<String, String> map = Book.viewIssuedBooks();
        for (Map.Entry<String, String> entry : map.entrySet()) {
            catalogueTextArea.append(entry.toString() +"\n");
        }
    }//GEN-LAST:event_issuedBooksBtnActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        PickUser userForm = new PickUser();
        userForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tableUpdate();
    }//GEN-LAST:event_formWindowActivated

    private void englishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishButtonActionPerformed
                englishButton.setText(bundle.getString("English"));
        frenchButton.setText(bundle.getString("French"));
        
        menuButton.setText(bundle.getString("ReturnToMenu"));     
        studentLabel.setText(bundle.getString("AddStudent"));
        
        stuIDLabel.setText(bundle.getString("SID"));
        issueStuID.setText(bundle.getString("SID"));
        returnStuIDLabel.setText(bundle.getString("SID"));
        
        nameLabel.setText(bundle.getString("Name"));
        phoneNumLabel.setText(bundle.getString("PhoneNum"));
        
        addStuBtn.setText(bundle.getString("Add"));
        addBookBtn.setText(bundle.getString("Add"));
        addBookLabel.setText(bundle.getString("AddBook"));
        
        issueSNNum.setText(bundle.getString("SN"));
        returnSNNum.setText(bundle.getString("SN"));
        addBookSNNum.setText(bundle.getString("SN"));
        
        titleLabel.setText(bundle.getString("Title"));
        authorLabel.setText(bundle.getString("Author"));
        publisherLabel.setText(bundle.getString("Publisher"));
        qtyLabel.setText(bundle.getString("Quantity"));
        priceLabel.setText(bundle.getString("Price"));
        qtyIssuedLabel.setText(bundle.getString("IssuedQTY"));
        dateLabel.setText(bundle.getString("Date"));
        
        issueLabel.setText(bundle.getString("IssueBook"));
        returnLabel.setText(bundle.getString("ReturnBook"));
        issueBookBtn.setText(bundle.getString("Issue"));
        returnBtn.setText(bundle.getString("Return"));
        
        listLabel.setText(bundle.getString("ListOfStudents"));
        catalogueLabel.setText(bundle.getString("BookCatalogue"));
        allBooksBtn.setText(bundle.getString("ViewBooks"));
        issuedBooksBtn.setText(bundle.getString("ViewIssuedBooks")); 
    }//GEN-LAST:event_englishButtonActionPerformed

    private void frenchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchButtonActionPerformed
        englishButton.setText(bundleFR.getString("English"));
        frenchButton.setText(bundleFR.getString("French"));
        
        menuButton.setText(bundleFR.getString("ReturnToMenu"));     
        studentLabel.setText(bundleFR.getString("AddStudent"));
        
        stuIDLabel.setText(bundleFR.getString("SID"));
        issueStuID.setText(bundleFR.getString("SID"));
        returnStuIDLabel.setText(bundleFR.getString("SID"));
        
        nameLabel.setText(bundleFR.getString("Name"));
        phoneNumLabel.setText(bundleFR.getString("PhoneNum"));
        
        addStuBtn.setText(bundleFR.getString("Add"));
        addBookBtn.setText(bundleFR.getString("Add"));
        addBookLabel.setText(bundleFR.getString("AddBook"));
        
        issueSNNum.setText(bundleFR.getString("SN"));
        returnSNNum.setText(bundleFR.getString("SN"));
        addBookSNNum.setText(bundleFR.getString("SN"));
        
        titleLabel.setText(bundleFR.getString("Title"));
        authorLabel.setText(bundleFR.getString("Author"));
        publisherLabel.setText(bundleFR.getString("Publisher"));
        priceLabel.setText(bundleFR.getString("Price"));
        qtyLabel.setText(bundleFR.getString("Quantity"));
        qtyIssuedLabel.setText(bundleFR.getString("IssuedQTY"));
        dateLabel.setText(bundleFR.getString("Date"));
        
        issueLabel.setText(bundleFR.getString("IssueBook"));
        returnLabel.setText(bundleFR.getString("ReturnBook"));
        issueBookBtn.setText(bundleFR.getString("Issue"));
        returnBtn.setText(bundleFR.getString("Return"));
        
        listLabel.setText(bundleFR.getString("ListOfStudents"));
        catalogueLabel.setText(bundleFR.getString("BookCatalogue"));
        allBooksBtn.setText(bundleFR.getString("ViewBooks"));
        issuedBooksBtn.setText(bundleFR.getString("ViewIssuedBooks"));    
    }//GEN-LAST:event_frenchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addBookAuthor;
    private javax.swing.JButton addBookBtn;
    private javax.swing.JTextField addBookDate;
    private javax.swing.JLabel addBookLabel;
    private javax.swing.JTextField addBookPrice;
    private javax.swing.JTextField addBookPublisher;
    private javax.swing.JTextField addBookQTY;
    private javax.swing.JTextField addBookQTYIssued;
    private javax.swing.JTextField addBookSN;
    private javax.swing.JLabel addBookSNNum;
    private javax.swing.JTextField addBookTitle;
    private javax.swing.JButton addStuBtn;
    private javax.swing.JButton allBooksBtn;
    private javax.swing.JLabel authorLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel catalogueLabel;
    private javax.swing.JTextArea catalogueTextArea;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JRadioButton englishButton;
    private javax.swing.JRadioButton frenchButton;
    private javax.swing.JButton issueBookBtn;
    private javax.swing.JTextField issueBookSNInput;
    private javax.swing.JTextField issueBookStuIDInput;
    private javax.swing.JLabel issueLabel;
    private javax.swing.JLabel issueSNNum;
    private javax.swing.JLabel issueStuID;
    private javax.swing.JButton issuedBooksBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listLabel;
    private javax.swing.JButton menuButton;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JLabel phoneNumLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JLabel qtyIssuedLabel;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JButton returnBtn;
    private javax.swing.JLabel returnLabel;
    private javax.swing.JLabel returnSNNum;
    private javax.swing.JTextField returnSerialNum;
    private javax.swing.JTextField returnStuID;
    private javax.swing.JLabel returnStuIDLabel;
    private javax.swing.JTextField stuIDInput;
    private javax.swing.JLabel stuIDLabel;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JTable studentTable;
    private javax.swing.JTextField textArea;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
